### ISSUE TITLE
Doesn't work on S21+ with April/May update 

### ISSUE THREAD

**Issue by bkdwt** [wr3cckl3ss1/system_shell_2#1]
I have tried on both patch's but I just get the "failed" message. 
![Screenshot_20230601_111821_#system_shell_2#](https://github.com/wr3cckl3ss1/system_shell_2/assets/51302074/a8859b60-e29a-4e63-8a6c-0bd2c6e0a519)

**Comment by wr3cckl3ss** [comment]
When you say both patches, what do you mean? Also this doesn't work on any firmware May 2023 and some April 2023. Your best way to know is by looking at when the build was made. Changes were made and sent around the first and second week of April. If your April firmware is of later in April when it was produced, then your firmware probably has the hard AOSP patch already.

**Comment by bkdwt** [comment]
> When you say both patches, what do you mean? Also this doesn't work on any firmware May 2023 and some April 2023. Your best way to know is by looking at when the build was made. Changes were made and sent around the first and second week of April. If your April firmware is of later in April when it was produced, then your firmware probably has the hard AOSP patch already.

I have tried with the April update and May update too. Both doesn't work. 
![Screenshot_20230601_111835_Settings](https://github.com/wr3cckl3ss1/system_shell_2/assets/51302074/6f6cbed3-bd59-4e2a-95d2-2e61948a1b40)
![Screenshot_20230601_193211_Settings](https://github.com/wr3cckl3ss1/system_shell_2/assets/51302074/1642240f-853e-41a2-a0b4-34fd097312fa)

**Comment by wr3cckl3ss** [comment]
May firmware is patched. So that's something you can not get past. As for April...look here.....

![Screenshot_20230601_174506_GitHub.jpg](https://github.com/wr3cckl3ss1/system_shell_2/assets/97212092/37d0851a-41ff-48a8-88e6-767cb43cd7e9)

Your device's firmware was built right around the same time the AOSP push was made and drafted. So it's possible, your device already has the patch even though its on April 2023 security patch. And without knowing exactly when or how Samsung pushed this into their builds, there's nothing I can do to help you. One option, i could suggest to you, is maybe going to March and if this still fails, then now this would be something i would take a look at. Good luck.
